name: Semantic Release for Apps

on:
  push:
    branches:
      - master
  
permissions: write-all

jobs:
  release:
    name: Semantic Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        id: checkout
        with:
          fetch-depth: 0
          token: ${{ secrets.PAT_GITHUB2 }}

      - name: Semantic Release
        uses: docker://ghcr.io/codfish/semantic-release-action:v2
        id: semantic
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_GITHUB2}}
        with:
          tag_format: 'v${version}'
          additional_packages: |
            [
              '@semantic-release/changelog',
              '@semantic-release/git'
            ]
          plugins: |
            [
              '@semantic-release/commit-analyzer',
              '@semantic-release/release-notes-generator',
              ['@semantic-release/changelog', {changelogTitle: '# CHANGELOG'}],
              '@semantic-release/github',
              '@semantic-release/git'
            ]
          branches: |
            [
              '+([0-9])?(.{+([0-9]),x}).x',
              'releases/+([0-9])?(.{+([0-9]),x}).x',
              'master',
              'next',
              'next-major',
              {
                name: 'beta',
                prerelease: true
              },
              {
                name: 'alpha',
                prerelease: true
              }
            ]
            